name: Personal Web Deployment

on:
   push:
    branches:
      - xyz

jobs:
  move-rename:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: move the files
        run : |
          echo "create folder - move all files to new folder"
          pwd
          cd ..
          ls

      - name: rename the files
        run : |
          echo "rename"
          pwd

  upload-gcp:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'